name: dms_env
channels:
  - r
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py37hc8dfbb8_1
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=py_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - bioconductor-biocgenerics=0.32.0=r36_0
  - bioconductor-biostrings=2.54.0=r36h516909a_0
  - bioconductor-iranges=2.20.0=r36h516909a_0
  - bioconductor-s4vectors=0.24.0=r36h516909a_0
  - bioconductor-xvector=0.26.0=r36h516909a_0
  - bioconductor-zlibbioc=1.32.0=r36h516909a_0
  - biopython=1.77=py37h7b6447c_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37h8f50634_1000
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=4.1.1=py_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=2.9.2=py37hb09aad4_0
  - curl=7.67.0=hbc83047_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.16=hb2f20db_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - fribidi=1.0.9=h7b6447c_0
  - gast=0.3.3=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_9
  - glib=2.63.1=h5a9c865_0
  - google-auth=1.19.0=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.14=h23475e2_0
  - grpcio=1.30.0=py37hb0870dc_0
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5py=2.10.0=nompi_py37h90cd8ad_103
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.6=nompi_h3c11f04_100
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - intel-openmp=2020.1=217
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - keras=2.3.1=py37_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - krb5=1.16.4=h173b8e3_0
  - libcurl=7.67.0=h20c2e04_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_1003
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=h8b12597_1
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - make=4.2.1=h1bed415_1
  - mako=1.1.0=py_0
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37hef1b27d_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - oauthlib=3.0.1=py_0
  - openssl=1.1.1g=h516909a_0
  - opt_einsum=3.2.1=py_0
  - pandas=1.0.5=py37h0573a6f_0
  - pango=1.42.4=h049681c_0
  - pcre=8.44=he6710b0_0
  - pip=20.1.1=py37_1
  - pixman=0.40.0=h7b6447c_0
  - protobuf=3.12.3=py37h3340039_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygpu=0.7.6=py37h03ebfcd_1001
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.1=h0371630_7
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37h8f50634_0
  - qt=5.9.7=h5867ecd_1
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-base=3.6.1=h9bb98a2_1
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-clipr=0.6.0=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h96ca727_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h96ca727_0
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-fansi=0.4.0=r36h96ca727_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-hms=0.4.2=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-lattice=0.20_38=r36h96ca727_0
  - r-lazyeval=0.2.2=r36h96ca727_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-mass=7.3_51.3=r36h96ca727_0
  - r-matrix=1.2_17=r36h96ca727_0
  - r-mgcv=1.8_28=r36h96ca727_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h29659fb_0
  - r-purrr=0.3.2=r36h96ca727_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-readr=1.3.1=r36h29659fb_0
  - r-reshape2=1.4.3=r36h29659fb_0
  - r-rlang=0.3.4=r36h96ca727_0
  - r-scales=1.0.0=r36h29659fb_0
  - r-stringdist=0.9.5.1=r36h96ca727_0
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-tibble=2.1.1=r36h96ca727_0
  - r-tidyr=0.8.3=r36h29659fb_0
  - r-tidyselect=0.2.5=r36h29659fb_0
  - r-utf8=1.1.4=r36h96ca727_0
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-withr=2.1.2=r36h6115d3f_0
  - readline=7.0=h7b6447c_5
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.2.0=py_0
  - rsa=4.6=pyh9f0ad1d_0
  - scikit-learn=0.23.1=py37h423224d_0
  - scipy=1.5.0=py37h0b6359f_0
  - setuptools=49.1.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tensorboard=2.2.2=py_0
  - tensorboard-plugin-wit=1.6.0=pyh9f0ad1d_0
  - tensorflow=2.2.0=mkl_py37h6e9ce2d_0
  - tensorflow-base=2.2.0=mkl_py37hd506778_0
  - tensorflow-estimator=2.2.0=pyh95af2a2_0
  - termcolor=1.1.0=py_2
  - theano=1.0.4=py37h3340039_1002
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tktable=2.10=h14c3975_0
  - tornado=6.0.4=py37h7b6447c_1
  - urllib3=1.25.9=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h8f50634_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
prefix: /home/djan/anaconda3/envs/dms_env

